# Generated by Django 4.0.4 on 2022-05-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achieve_achievements_applications_chat_child_users_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
