# Generated by Django 4.0.4 on 2022-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_drop_all_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
