# Generated by Django 4.0.4 on 2022-05-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passport_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
        migrations.DeleteModel(
            name='User_Data',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
