# Generated by Django 4.0.4 on 2022-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_passport_user_data_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentUsers',
            new_name='Parent_Users',
        ),
        migrations.AddField(
            model_name='teacher_users',
            name='diploma',
            field=models.CharField(default=-1994, max_length=255),
            preserve_default=False,
        ),
    ]
